### ISSUE TITLE
I can't do a google search

### ISSUE THREAD

**Issue by Arinze1020** [adnane-X-tebbaa/Katana#15]
am getting this error

Traceback (most recent call last):
  File "kds.py", line 67, in <module>
    from Modes import Scada
  File "/home/###/Desktop/bee/Katana/Modes/Scada.py", line 94, in <module>
    for gamma in search(query, tld=beta,stop=50, num=10,pause=2): 
TypeError: search() got an unexpected keyword argument 'tld'

**Comment by adnane-X-tebbaa** [comment]
What Python Version you use?
Thanks!

**Comment by Arinze1020** [comment]
Am using 3.8

**Comment by Arinze1020** [comment]
Do you have a preferred version

**Comment by adnane-X-tebbaa** [comment]
yes! Katana will not work with py 3.8 and above 
only python 3.7 and below 
please let me know if it works so i can close this issue
thanks!

**Comment by Arinze1020** [comment]
ok thanks, I will run a check on it 
Good work
